import type { Metadata } from "next";
import { Inter } from "next/font/google";

import './style/globals.css'
import './style/fonts.css'

import Header from '@/components/Header'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='w-full min-h-screen flex flex-col'>
        <Header />
        {children}
        <Footer>
          @2024 Joel Hellberg. Denna hemsida är byggd av studenter vid LiU
        </Footer>
      </body>
    </html>
  );
}
