import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Sponsor from '@/components/Sponsor'
import './style/globals.css'
import './style/fonts.css'

import Header from '@/components/Header'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Basåret",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='w-full min-h-screen flex flex-col'>
        <Header />
        {children}

        {/* Ads */}
        <div className="
        flex flex-wrap justify-evenly items-center w-full py-20 px-32
        handheld:px-20 handheld:flex-col handheld:space-y-10
        mobile:px-8      
        ">
          <Sponsor company1="ICA" company2="" className="grow-1 h-52 w-2/3 mobile:w-full" />
          {/*<Sponsor company1="NAB" company2="Voyado" className="grow-1 h-48 w-1/3 mobile:w-3/5" />
          <Sponsor company1="Micropower" company2="" className="grow-2 h-48 w-2/3 mobile:w-full" />*/}
        </div>
        <Footer>
          @2024 Joel Hellberg. Denna hemsida är byggd av studenter vid LiU
        </Footer>
      </body>
    </html>
  );
}
